### ISSUE TITLE
"wq phonegap" command crashes on generating 9-Patch files

### ISSUE THREAD

**Issue by tomaszn** [wq/wq.app#108]
```
▪ wq phonegap 1.0                                                                                                
Generating icons for android: 36, 48, 72, 96, 144, 192                                                             
Generating icons for ios: 29, 40, 50, 57, 58, 60, 72, 76, 80, 87, 100, 114, 120, 144, 152, 167, 180                
Generating icons for windows: 30, 44, 50, 70, 71, 106, 120, 150, 170, 310x150, 310, 360, 744x360                   
Generating icons for android-splash: 100.9, 160.9, 240.9, 360.9, 480.9, 640.9                                      
Traceback (most recent call last):
  File "/home/user/venv/bin/wq", line 11, in <module>
    sys.exit(wq())
  File "/home/user/venv/lib/python3.6/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/venv/lib/python3.6/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/user/venv/lib/python3.6/site-packages/wq/core/decorators.py", line 19, in invoke
    return super(ConfigGroup, self).invoke(ctx)
  File "/home/user/venv/lib/python3.6/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/venv/lib/python3.6/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/venv/lib/python3.6/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/user/venv/lib/python3.6/site-packages/click/decorators.py", line 63, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/user/venv/lib/python3.6/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/user/venv/lib/python3.6/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/venv/lib/python3.6/site-packages/wq/app/build/phonegap.py", line 98, in phonegap
    index_html=conf['index_html'],
  File "/home/user/venv/lib/python3.6/site-packages/wq/app/build/phonegap.py", line 155, in create_zipfile
    size=[platform],
  File "/home/user/venv/lib/python3.6/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/user/venv/lib/python3.6/site-packages/wq/app/build/icons.py", line 198, in icons
    icon = ImageOps.expand(icon, (1, 1, 1, 1), (0, 0, 0, 0))
  File "/home/user/venv/lib/python3.6/site-packages/PIL/ImageOps.py", line 366, in expand
    out = Image.new(image.mode, (width, height), _color(fill, image.mode))
  File "/home/user/venv/lib/python3.6/site-packages/PIL/Image.py", line 2375, in new
    return Image()._new(core.fill(mode, size, color))
TypeError: function takes at most 2 arguments (4 given)
```

**Comment by sheppard** [comment]
Thanks for reporting this.  I can cherry-pick commit f491f870c0b86645cdb17ab3ef071bfce0ba71c3 into my master branch if that works for you.

**Comment by sheppard** [comment]
This is released in [wq.app 1.1.1](https://github.com/wq/wq.app/releases/v1.1.1).
