### ISSUE TITLE
Error when trying to Build

### ISSUE THREAD

**Issue by joshglenn** [wq/wq.app#53]
When I try to build, I get this error:

```
Now opening... ../htdocs-build/build.txt
Traceback (most recent call last):
  File "/Users/josh/.virtualenvs/wq1/bin/wq", line 9, in <module>
    load_entry_point('wq.core==0.8.0', 'console_scripts', 'wq')()
  File "/Users/josh/.virtualenvs/wq1/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/josh/.virtualenvs/wq1/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/josh/.virtualenvs/wq1/lib/python2.7/site-packages/wq/core/decorators.py", line 19, in invoke
    return super(ConfigGroup, self).invoke(ctx)
  File "/Users/josh/.virtualenvs/wq1/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/josh/.virtualenvs/wq1/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/josh/.virtualenvs/wq1/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/josh/.virtualenvs/wq1/lib/python2.7/site-packages/click/decorators.py", line 63, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/josh/.virtualenvs/wq1/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/josh/.virtualenvs/wq1/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/josh/.virtualenvs/wq1/lib/python2.7/site-packages/wq/app/build/builder.py", line 56, in build
    ctx.invoke(appcache, version=version)
  File "/Users/josh/.virtualenvs/wq1/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/josh/.virtualenvs/wq1/lib/python2.7/site-packages/click/decorators.py", line 63, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/josh/.virtualenvs/wq1/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/josh/.virtualenvs/wq1/lib/python2.7/site-packages/wq/app/build/appcache.py", line 48, in appcache
    s_js, b_js = _parse_js_buildfile(outdir + '/build.txt')
  File "/Users/josh/.virtualenvs/wq1/lib/python2.7/site-packages/wq/app/build/appcache.py", line 80, in _parse_js_buildfile
    text = open(filename).read()
IOError: [Errno 2] No such file or directory: '../htdocs-build/build.txt'
```

It's obviously looking for build.txt. Where is this build.txt file? What creates build.txt in the first place?

**Comment by sheppard** [comment]
build.txt is created by r.js during the optimize step.  So, this is related to #52, but that's not obvious, as you have to scroll up to see the r.js error.  It would be better to catch and summarize the r.js results so it's clearer what's going on (see #46).

**Comment by joshglenn** [comment]
Solved. See solution to #52.
