### ISSUE TITLE
No such file or directory: '../htdocs-build/build.txt'

### ISSUE THREAD

**Issue by narnikgamarnikus** [wq/wq.app#89]
Hello.

If I try run command 'qw build 0.0.1' in the `/app` directory,  I get error `FileNotFoundError: [Errno 2] No such file or directory: '../htdocs-build/build.txt'`

Traceback:

```
js/data/version.js: 0.0.1
js/data/templates.js: 8 objects collected from ../templates
css/themes.css compiled from scss/themes.scss
####################
Optimizing with r.js
Optimizing (standard.keepLines.keepWhitespace) CSS file: /home/narnik/Программы/WQProjects/firstexample/firstexample/htdocs-build/css/firstexample/main.css
Optimizing (standard.keepLines.keepWhitespace) CSS file: /home/narnik/Программы/WQProjects/firstexample/firstexample/htdocs-build/css/firstexample/responsive.css
Optimizing (standard.keepLines.keepWhitespace) CSS file: /home/narnik/Программы/WQProjects/firstexample/firstexample/htdocs-build/css/firstexample.css
lib/leaflet.css
  URL not a relative URL, skipping: #default#VML
Optimizing (standard.keepLines.keepWhitespace) CSS file: /home/narnik/Программы/WQProjects/firstexample/firstexample/htdocs-build/css/lib/highlight.css
Optimizing (standard.keepLines.keepWhitespace) CSS file: /home/narnik/Программы/WQProjects/firstexample/firstexample/htdocs-build/css/lib/jquery.mobile.css
Optimizing (standard.keepLines.keepWhitespace) CSS file: /home/narnik/Программы/WQProjects/firstexample/firstexample/htdocs-build/css/lib/jquery.mobile.icons.css
Optimizing (standard.keepLines.keepWhitespace) CSS file: /home/narnik/Программы/WQProjects/firstexample/firstexample/htdocs-build/css/lib/jquery.mobile.structure.css
Optimizing (standard.keepLines.keepWhitespace) CSS file: /home/narnik/Программы/WQProjects/firstexample/firstexample/htdocs-build/css/lib/leaflet.css
Optimizing (standard.keepLines.keepWhitespace) CSS file: /home/narnik/Программы/WQProjects/firstexample/firstexample/htdocs-build/css/lib/leaflet.draw.css
Optimizing (standard.keepLines.keepWhitespace) CSS file: /home/narnik/Программы/WQProjects/firstexample/firstexample/htdocs-build/css/lib/leaflet.markercluster.css
Optimizing (standard.keepLines.keepWhitespace) CSS file: /home/narnik/Программы/WQProjects/firstexample/firstexample/htdocs-build/css/lib/wq/app.css
Optimizing (standard.keepLines.keepWhitespace) CSS file: /home/narnik/Программы/WQProjects/firstexample/firstexample/htdocs-build/css/themes.css

Tracing dependencies for: firstexample
Error: ENOENT: no such file or directory, open '/home/narnik/Программы/WQProjects/firstexample/firstexample/htdocs-build/js/lib/jquery.js'
In module tree:
    firstexample
      firstexample/main
        wq/app

Error: Error: ENOENT: no such file or directory, open '/home/narnik/Программы/WQProjects/firstexample/firstexample/htdocs-build/js/lib/jquery.js'
In module tree:
    firstexample
      firstexample/main
        wq/app

    at Object.fs.openSync (fs.js:651:18)

Optimization complete
####################
Traceback (most recent call last):
  File "/home/narnik/Программы/WQProjects/env/bin/wq", line 11, in <module>
    sys.exit(wq())
  File "/home/narnik/Программы/WQProjects/env/lib/python3.6/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/narnik/Программы/WQProjects/env/lib/python3.6/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/narnik/Программы/WQProjects/env/lib/python3.6/site-packages/wq/core/decorators.py", line 19, in invoke
    return super(ConfigGroup, self).invoke(ctx)
  File "/home/narnik/Программы/WQProjects/env/lib/python3.6/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/narnik/Программы/WQProjects/env/lib/python3.6/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/narnik/Программы/WQProjects/env/lib/python3.6/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/narnik/Программы/WQProjects/env/lib/python3.6/site-packages/click/decorators.py", line 63, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/narnik/Программы/WQProjects/env/lib/python3.6/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/narnik/Программы/WQProjects/env/lib/python3.6/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/narnik/Программы/WQProjects/env/lib/python3.6/site-packages/wq/app/build/builder.py", line 56, in build
    ctx.invoke(appcache, version=version)
  File "/home/narnik/Программы/WQProjects/env/lib/python3.6/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/narnik/Программы/WQProjects/env/lib/python3.6/site-packages/click/decorators.py", line 63, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/narnik/Программы/WQProjects/env/lib/python3.6/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/narnik/Программы/WQProjects/env/lib/python3.6/site-packages/wq/app/build/appcache.py", line 48, in appcache
    s_js, b_js = _parse_js_buildfile(outdir + '/build.txt')
  File "/home/narnik/Программы/WQProjects/env/lib/python3.6/site-packages/wq/app/build/appcache.py", line 79, in _parse_js_buildfile
    text = open(filename).read()
FileNotFoundError: [Errno 2] No such file or directory: '../htdocs-build/build.txt'

```

**Comment by sheppard** [comment]
Hi, it looks like your `js/lib` folder isn't referenced correctly, based on the r.js error in the middle of the log.  The linking is supposed to happen automatically, but it doesn't seem to have worked in this case.  It should be a symlink, something like this:

app/js/lib -> /home/narnik/Программы/WQProjects/env/lib/python3.6/site-packages/wq/app/js

The build.txt error is a secondary error due to the r.js error not being handled properly.  I am working on a better method for running r.js which will make sure that only the r.js error is reported rather than waiting to fail on build.txt (see #92).
